### ISSUE TITLE
🕷[Inline View][Minor] Moving a Message which is open in Inline View opens the Folderdialog at the opened Mail

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#244]
![crypth_move_email](https://user-images.githubusercontent.com/1238238/34501887-3878945c-f011-11e7-931f-1895db4d22bd.png)

When an EMail is open in the Inline View the Move Dialog for the Folderdialog popsup on that EMail instead of on the Top under the Move Button.
[WARNING] This Behaviour is very good for mobile usage.
On Desktop this Behaviour is unexpected and regularly makes you search the Dialog.

This does not happen if the selected EMail is closed, then the Popup is, as expected, on the top below the Move Button.

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
Thanks for the report. I'm not surprised by this. Inline view is buggy. It's gotten better since I prematurely committed it, but still buggy :)

**Comment by ulfgebhardt** [comment]
I have to admit, im currently not on the latest commit - so there might be things in my latest bugreports which are already fixed.

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
No worries, I always appreciate the feedback. This one is likely still broken in the latest code. I will check it out.

**Comment by jasonmunro** [comment]
@ulfgebhardt pushed a fix for this last night, let me know when you can!

**Comment by ulfgebhardt** [comment]
<3 ur the best!
