### ISSUE TITLE
Sometimes, I click reply, or reply to all, and the email is blank. If I cancel and try again, it works OK.

### ISSUE THREAD

**Issue by marclaporte** [jasonmunro/cypht#420]
Seen by at least Jason and myself. No pattern to reproduce yet.

https://gitter.im/cypht-org/community?at=5f307abefe39ca5d65902d7c

**Comment by marclaporte** [comment]
@jasonmunro Can you think of anything I could do to detect the pattern?

**Comment by marclaporte** [comment]
I have been to reproduce something odd: forwarded message as attachment appears more than once:
![Screenshot_20201002-134717](https://user-images.githubusercontent.com/1004261/94954081-8f51e500-04b6-11eb-9cc7-2d6edbac5010.png)

To do this
* On a message, click "forward", then back (with your browser), then forward again, etc.

**Comment by jasonmunro** [comment]
This issue should be resolved in the master branch

**Comment by marclaporte** [comment]
@jasonmunro: I still get many attachments when doing:

"On a message, click "forward", then back (with your browser), then forward again, etc."

**Comment by jasonmunro** [comment]
that should be it's own issue as it is unrelated to this particular problem

**Comment by marclaporte** [comment]
I confirm blank emails are solved by https://github.com/jasonmunro/cypht/commit/2a9060a17acf6b19abdd8f0a4e9dc84a3fb42ef7

Thanks!

**Comment by marclaporte** [comment]
I am still getting some. But it happens less often.

I also noticed some on "forward"

**Comment by marclaporte** [comment]
The trick I described above (On a message, click "forward", then back (with your browser), then forward again, etc.) not longer works because issue has been fixed by https://github.com/jasonmunro/cypht/pull/453

blank message on reply remains.

**Comment by marclaporte** [comment]
This problem persists to this day, but I hope it is the same root cause as discussed at https://github.com/jasonmunro/cypht/pull/508 and thus, be resolved soon.

**Comment by marclaporte** [comment]
So I was still having this intermittent problem, so @kroky dove in.

It turns out to be a race condition in AJAX requests executed in the background when Cypht is integrated in Tiki, and when "Session storage location" is DB. Switching to "Default (from php.ini) solves it. We'll experiment a bit more and add a fix to Tiki.

**Comment by marclaporte** [comment]
For the record: https://gitlab.com/tikiwiki/tiki/-/commit/5281f16493abe46df57678ec329f8b6124d8aa8e
